import React, { useState } from 'react';
import './App.css';
import CompareList from './pages/comapre-list';
import UploadFile from './pages/upload-file';

// const origin =
//   'ATGCAGCGAAGAGGGAGCAATCTAGTAAGTGTGCTTTTCTTTTTCATCGCTAGGTGGGGTAATATCATACATAGGATCGTGTGGGGGCTCTCCCAACCGCACCAGCCCCGTGTCCATGTACAGTGAGAACTCCAACAGCAGCCTGCAGTCCTTTACGCAACCCTGCTTTGGTTCTTCATTTCCACCATCCCCCAATGGATCGCATGATTCCTCTCGCATGTACACCAGCAGCAGCAGCAGCTCGAGTTCTGGATCAGGAGAGGAGGGAAACTCATCATGCTCTAGTGGATCCCCAAGAGGCCGTGATGATGGTGGAAGTGCACGCAATTCACCCAACAAATCAGTTGCCACCCTTACTAGTAAGTGATAAGAACCATACCTGATTAATGTAGAGTATGGCATCCAGGAGAACGATTATTATAACATCTAACTTTCCATCCAGAGCTGAATGGAATGGTGTTGCTGTGCAAAGTGTGTGGCGATGTGGCTTCCGGTTTTCACTATGGTGTCCATGCCTGTGAGGGCTGCAAGGTAATTAAATAGCATCTGTTTATATTTGCAAGAGTTTAATATACATTTTACTTCTTAATTAAAGCTTTTGTTTAAACAAAATTTACATTTACGTTATCTGCATTGTCCACAGGGTTTCTTTCGACGCAGCATCCAGCAGAACATTCAGTACAAAAAGTGCCTGAAGAATGAAACTTGTACCATTATGAGGATCAACCGAACCGGTGCCAGCAGTGCCGTTTCAAAAAGTGTCTGTCTGTGGGAATGTCCCGAGACGGTGA';

// const dataSource = [
//   {
//       "key": "572-724-10689-10841",
//       "rate": "99.346",
//       "originStart": 572,
//       "originEnd": 724,
//       "targetStart": 10689,
//       "targetEnd": 10841,
//       anomaly: true,
//       "originValue": "ATACATTTTACTTCTTAATTAAAGCTTTTGTTTAAACAAAATTTACATTTACGTTATCTGCATTGTCCACAGGGTTTCTTTCGACGCAGCATCCAGCAGAACATTCAGTACAAAAAGTGCCTGAAGAATGAAACTTGTACCATTATGAGGATC",
//       "targetValue": "ATACATTTTACTTCTTAATTAAAGCTTTTGTTTAAACAAAATTTAAATTTACGTTATCTGCATTGTCCACAGGGTTTCTTTCGACGCAGCATCCAGCAGAACATTCAGTACAAAAAGTGCCTGAAGAATGAAACTTGTACCATTATGAGGATC"
//   },
//   {
//       "key": "568-719-10389-10540",
//       "rate": "99.342",
//       "originStart": 568,
//       "originEnd": 719,
//       "targetStart": 10389,
//       "targetEnd": 10540,
//       "originValue": "TAATATACATTTTACTTCTTAATTAAAGCTTTTGTTTAAACAAAATTTACATTTACGTTATCTGCATTGTCCACAGGGTTTCTTTCGACGCAGCATCCAGCAGAACATTCAGTACAAAAAGTGCCTGAAGAATGAAACTTGTACCATTATGA",
//       "targetValue": "TAATATACATTTTACTTCTTAATTAAAGCTTTTGTTTAAACAAAATTTAAATTTACGTTATCTGCATTGTCCACAGGGTTTCTTTCGACGCAGCATCCAGCAGAACATTCAGTACAAAAAGTGCCTGAAGAATGAAACTTGTACCATTATGA"
//   }
// ]

function App() {
  const [showTable, setShowTable] = useState(false);
  const [originContent, setOriginContent] = useState('');
  const [data, setData] = useState([]);
  return (
    <div className='app'>
      <div className='app-title'>对比序列v0.2</div>
      <div className='app-content'>
        {!showTable ? (
          <UploadFile
            originContent={originContent}
            setShowTable={setShowTable}
            setOriginContent={setOriginContent}
            setData={setData}
          />
          ) : (
            <CompareList
            data={data}
            originContent={originContent}
            setShowTable={setShowTable}
            setData={setData}
          />
        )}
      </div>
    </div>
  );
}

export default App;
